version: "3"
services:
    db:
      image: mysql:8.0.26
      restart: always
      deploy:
        resources:
            limits:
              cpus: '1.0'
              memory: 1024M
            reservations:
              cpus: '0.5'
              memory: 512M
      command:
        - --lower_case_table_names=1
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=mydb
        - MYSQL_ROOT_PASSWORD=pix123!
        - TZ=Asia/Seoul
      volumes:
        - D:\fastcampus\backend\docker-compose\db:/var/lib/mysql